# Generated by Django 3.0.9 on 2020-11-24 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('desc', models.TextField()),
                ('photo', models.ImageField(default='media\\default\x0cuchka.jpg', upload_to='blog')),
            ],
        ),
    ]
